using InterceptionSampleMongoApp.MongoDB;
using Xunit;

namespace InterceptionSampleMongoApp;

[CollectionDefinition(InterceptionSampleMongoAppTestConsts.CollectionDefinitionName)]
public class InterceptionSampleMongoAppDomainCollection : InterceptionSampleMongoAppMongoDbCollectionFixtureBase
{

}
