// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using EShopOnAbp.CatalogService.Products;

// ReSharper disable once CheckNamespace
namespace EShopOnAbp.CatalogService.Products.ClientProxies
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IPublicProductAppService), typeof(PublicProductClientProxy))]
    public partial class PublicProductClientProxy : ClientProxyBase<IPublicProductAppService>, IPublicProductAppService
    {
        public virtual async Task<ListResultDto<ProductDto>> GetListAsync()
        {
            return await RequestAsync<ListResultDto<ProductDto>>(nameof(GetListAsync));
        }

        public virtual async Task<ProductDto> GetAsync(Guid id)
        {
            return await RequestAsync<ProductDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
            {
                { typeof(Guid), id }
            });
        }
    }
}
