// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using BookStore.Books;

// ReSharper disable once CheckNamespace
namespace BookStore.Books.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBookV5AppService), typeof(BookV5ClientProxy))]
public partial class BookV5ClientProxy : ClientProxyBase<IBookV5AppService>, IBookV5AppService
{
    public virtual async Task<BookDto> GetAsync()
    {
        return await RequestAsync<BookDto>(nameof(GetAsync));
    }

    public virtual async Task<BookDto> UpdateAsync(string isbn)
    {
        return await RequestAsync<BookDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), isbn }
        });
    }
}
