// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using BookStore.Books;

// ReSharper disable once CheckNamespace
namespace BookStore.Books.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBookV4AppService), typeof(BookV4ClientProxy))]
public partial class BookV4ClientProxy : ClientProxyBase<IBookV4AppService>, IBookV4AppService
{
    public virtual async Task<BookDto> GetAsync()
    {
        return await RequestAsync<BookDto>(nameof(GetAsync));
    }
}
