export const mockMembers = [
  {
    fullName: 'John Doe',
    username: 'John.Doe',
    phone: '+1-202-555-0125',
    email: 'john.doe@example.com',
    parents: ['Customer Relations', 'Marketing'],
  },
  {
    fullName: 'Darrion Walter',
    username: 'Darrion.Walter',
    phone: '+1-262-155-0355',
    email: 'Darrion_Walter@example.com',
    parents: ['Marketing'],
  },
  {
    fullName: 'Rosa Labadie',
    username: 'Rosa.Labadie',
    phone: '+1-262-723-2255',
    email: 'Rosa.Labadie@example.com',
    parents: ['Marketing', 'Buying'],
  },
  {
    fullName: 'Adelle Hills',
    username: 'Adelle.Hills',
    phone: '+1-491-112-9011',
    email: 'Adelle.Hills@example.com',
    parents: ['Buying'],
  },
  {
    fullName: 'Brian Hane',
    username: 'Brian.Hane',
    phone: '+1-772-509-1823',
    email: 'Brian.Hane@example.com',
    parents: ['Human Resources'],
  },
  {
    fullName: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    phone: '1-770-736-8031 x56442',
    parents: ['Human Resources'],
  },
  {
    fullName: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    phone: '010-692-6593',
    parents: ['Human Resources', 'Customer Relations'],
  },
  {
    fullName: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    phone: '1-463-123-4447',
    parents: ['Customer Relations'],
  },
  {
    fullName: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    phone: '493-170-9623',
    parents: ['Customer Relations', 'Human Resources'],
  },
  {
    fullName: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    phone: '(254)954-1289',
    parents: ['Customer Relations'],
  },
  {
    fullName: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    phone: '1-477-935-8478',
    parents: ['Buying'],
  },
  {
    fullName: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    phone: '210.067.6132',
    parents: ['Buying'],
  },
  {
    fullName: 'Nicholas Runolf',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    phone: '586.493.6943',
    parents: ['Buying'],
  },
  {
    fullName: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    phone: '(775)976-6794',
    parents: ['Marketing'],
  },
  {
    fullName: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    phone: '024-648-3804',
    parents: ['Customer Relations'],
  },
];
