start powershell .\01_AuthServer.ps1
start powershell .\02_IdentityService.ps1
start powershell .\03_TenantManagementService.ps1
start powershell .\04_BloggingService.ps1
start powershell .\05_ProductService.ps1
start powershell .\06_InternalGateway.ps1
start powershell .\07_BackendAdminAppGateway.ps1
start powershell .\08_PublicWebSiteGateway.ps1
start powershell .\09_BackendAdminApp.ps1
start powershell .\10_PublicWebSite.ps1