// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using EShopOnAbp.PaymentService.PaymentMethods;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace EShopOnAbp.PaymentService.Controllers.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPaymentMethodAppService), typeof(PaymentMethodClientProxy))]
public partial class PaymentMethodClientProxy : ClientProxyBase<IPaymentMethodAppService>, IPaymentMethodAppService
{
    public virtual async Task<List<PaymentMethodDto>> GetListAsync()
        {
            return await RequestAsync<List<PaymentMethodDto>>(nameof(GetListAsync));
        }
}
