// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using KeycloakDemo.Identity;

// ReSharper disable once CheckNamespace
namespace KeycloakDemo.Controllers.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityProfileAppService), typeof(IdentityProfileClientProxy))]
public partial class IdentityProfileClientProxy : ClientProxyBase<IIdentityProfileAppService>, IIdentityProfileAppService
{
    public virtual async Task CreateOrUpdateAsync()
    {
        await RequestAsync(nameof(CreateOrUpdateAsync));
    }
}
