using Xunit;

namespace InterceptionSampleMongoApp.MongoDB;

[CollectionDefinition(InterceptionSampleMongoAppTestConsts.CollectionDefinitionName)]
public class InterceptionSampleMongoAppMongoCollection : InterceptionSampleMongoAppMongoDbCollectionFixtureBase
{

}
