using Volo.Abp;

namespace OutputCachingMiddleware.EntityFrameworkCore;

public abstract class OutputCachingMiddlewareEntityFrameworkCoreTestBase : OutputCachingMiddlewareTestBase<OutputCachingMiddlewareEntityFrameworkCoreTestModule>
{

}
