namespace SignInWithoutSpecifyingTenant;

public abstract class SignInWithoutSpecifyingTenantApplicationTestBase : SignInWithoutSpecifyingTenantTestBase<SignInWithoutSpecifyingTenantApplicationTestModule>
{

}
